package com.tms.edi.enums;

public enum ErrorType {
    MISSING_MANDATORY_FIELD,
    TRANSFORMATION_FAILURE,
    INVALID_DATA_FORMAT,
    LOOKUP_VALUE_NOT_FOUND,
    DUPLICATE_ORDER_ID,
    SCHEMA_PARSE_ERROR,
    DB_INSERT_FAILURE,
    VALIDATION_RULE_FAIL,
    TIMEOUT,
    CHECKSUM_MISMATCH
}
