insert into reference_master (category, code, name, description, extra_json, sort_order, is_active, created_at, updated_at)
values
('COUNTRY','SA','Saudi Arabia','Country master',null,30,true,now(),now()),
('ADDRESS_TYPE','RETURN','Return Address','Address type',null,40,true,now(),now()),
('REGION','AE-NORTH','Northern Emirates','Region','{"countryCode":"AE"}',30,true,now(),now()),
('ZONE','AE-DXB-FREEZONE','Dubai Free Zone','Zone','{"regionCode":"AE-NORTH"}',30,true,now(),now()),
('STATE','DU','Dubai','State','{"countryCode":"AE"}',40,true,now(),now()),
('STATE','AZ','Abu Dhabi','State','{"countryCode":"AE"}',50,true,now(),now()),
('CITY','DXB','Dubai','City','{"stateCode":"DU","countryCode":"AE","regionCode":"AE-NORTH","zoneCode":"AE-DXB-FREEZONE"}',40,true,now(),now()),
('CITY','AUH','Abu Dhabi','City','{"stateCode":"AZ","countryCode":"AE","regionCode":"AE-NORTH"}',50,true,now(),now()),
('POSTAL_CODE','00000','00000','Postal code','{"cityCode":"DXB","stateCode":"DU","countryCode":"AE","regionCode":"AE-NORTH","zoneCode":"AE-DXB-FREEZONE"}',40,true,now(),now()),
('POSTAL_CODE','51133','51133','Postal code','{"cityCode":"AUH","stateCode":"AZ","countryCode":"AE","regionCode":"AE-NORTH"}',50,true,now(),now())
on conflict (category, code) do nothing;

insert into address_master (
    address_code,
    address_type,
    entity_type,
    entity_id,
    address_line1,
    address_line2,
    address_line3,
    landmark,
    city,
    district,
    state_province,
    postal_code,
    country_code,
    country_name,
    latitude,
    longitude,
    timezone,
    is_primary,
    is_active,
    validation_status,
    created_at,
    updated_at
)
values
(
    'ADDR-BLR-HQ',
    'BILLING',
    'CUSTOMER',
    1001,
    'No. 45 Richmond Road',
    'Ashok Nagar',
    null,
    'Near MG Road Metro',
    'Bengaluru',
    'Bengaluru Urban',
    'Karnataka',
    '560001',
    'IN',
    'India',
    12.9716,
    77.5946,
    'Asia/Kolkata',
    true,
    true,
    'VALID',
    now(),
    now()
),
(
    'ADDR-DEL-WH1',
    'SHIPPING',
    'WAREHOUSE',
    2001,
    'Plot 18 Logistics Park',
    'NH-8',
    null,
    'Near Aerocity',
    'Delhi',
    'New Delhi',
    'Delhi',
    '110001',
    'IN',
    'India',
    28.6139,
    77.2090,
    'Asia/Kolkata',
    false,
    true,
    'VALID',
    now(),
    now()
),
(
    'ADDR-DXB-HUB',
    'PICKUP',
    'SUPPLIER',
    3001,
    'Warehouse 12, Jebel Ali',
    'South Zone',
    null,
    'Gate 4',
    'Dubai',
    'Jebel Ali',
    'Dubai',
    '00000',
    'AE',
    'United Arab Emirates',
    25.0657,
    55.1713,
    'Asia/Dubai',
    false,
    true,
    'PENDING',
    now(),
    now()
)
on conflict (address_code) do update
set
    address_type = excluded.address_type,
    entity_type = excluded.entity_type,
    entity_id = excluded.entity_id,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    address_line3 = excluded.address_line3,
    landmark = excluded.landmark,
    city = excluded.city,
    district = excluded.district,
    state_province = excluded.state_province,
    postal_code = excluded.postal_code,
    country_code = excluded.country_code,
    country_name = excluded.country_name,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    timezone = excluded.timezone,
    is_primary = excluded.is_primary,
    is_active = excluded.is_active,
    validation_status = excluded.validation_status,
    updated_at = now();
